name: Renovate

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.3
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          renovate-version: 'latest' # or specify a specific version if needed

      - name: Install PDM
        run: pip install pdm

      - name: Update pdm.lock
        run: pdm sync

      - name: Commit changes
        run: |
          git config --global user.name 'Renovate Bot'
          git config --global user.email 'renovate@your-domain.com'
          git add --all
          git commit -m "Update dependencies and pdm.lock"
          git push origin main